"""Tests for scripts/dep-churn-lib.sh -- update-deps.sh's VERSION DIFF and the skip
policy for its churn-evaluation stub ticket (lode-i642).

Written during the technical review of lode-i642, which shipped this logic with no
test at all and, as a direct consequence, shipped it DEAD: the raw change lines were
computed into a global from inside a function that update-deps.sh only ever calls as
``DIFF_TEXT="$(print_version_diff ...)"``. Command substitution runs in a subshell, so
the global never reached the parent scope, the "no version changes" guard was
unconditionally true, and the feature's whole point -- filing the stub ticket -- could
never happen on any input. Both quality gates were green over that. The standing rule
it cost (a sourceable shell lib returns on stdout and holds no cross-call state) is in
docs/stack.md; this file is where the incident itself is remembered.

So the bar here is not "the noise gate has a unit test". It is that the *decision* --
whether a given run files or skips, and in which order the skip reasons win -- is
exercised end to end through ``dep_stub_skip_reason``, the one function update-deps.sh
now consults. ``test_update_deps_never_assigns_changes_raw_in_a_function`` pins the
caller-side half that no pure-function test can reach.

Every test runs the ACTUAL shell via ``bash``; nothing is reimplemented in Python.
"""

from __future__ import annotations

import re
import shlex
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
LIB = REPO_ROOT / "scripts" / "dep-churn-lib.sh"
UPDATE_DEPS = REPO_ROOT / "scripts" / "update-deps.sh"


def _run(script: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", "-c", f'set -uo pipefail\n. "{LIB}"\n{script}'],
        capture_output=True,
        text=True,
        check=False,
    )


def _lock(tmp_path: Path, name: str, pins: dict[str, str]) -> Path:
    """A minimal requirements.lock-shaped file: name==version plus hash noise."""
    path = tmp_path / name
    body = "".join(
        f"{pkg}=={ver} \\\n    --hash=sha256:{'0' * 64}\n" for pkg, ver in pins.items()
    )
    path.write_text("# generated by uv\n" + body, encoding="utf-8")
    return path


# --------------------------------------------------------------------------
# dep_changes_raw
# --------------------------------------------------------------------------


def test_changes_raw_reports_only_moved_packages(tmp_path: Path) -> None:
    old = _lock(tmp_path, "old.lock", {"alpha": "1.2.3", "beta": "2.0.0"})
    new = _lock(tmp_path, "new.lock", {"alpha": "1.2.4", "beta": "2.0.0"})
    got = _run(f'dep_changes_raw "{old}" "{new}"')
    assert got.returncode == 0, got.stderr
    assert got.stdout.strip() == "alpha\t1.2.3\t1.2.4"


def test_changes_raw_marks_additions_and_removals(tmp_path: Path) -> None:
    old = _lock(tmp_path, "old.lock", {"gone": "1.0.0"})
    new = _lock(tmp_path, "new.lock", {"fresh": "9.9.9"})
    lines = set(_run(f'dep_changes_raw "{old}" "{new}"').stdout.split("\n")) - {""}
    assert lines == {"fresh\t(none)\t9.9.9", "gone\t1.0.0\t(none)"}


def test_changes_raw_empty_when_identical(tmp_path: Path) -> None:
    old = _lock(tmp_path, "old.lock", {"alpha": "1.2.3"})
    new = _lock(tmp_path, "new.lock", {"alpha": "1.2.3"})
    assert _run(f'dep_changes_raw "{old}" "{new}"').stdout.strip() == ""


# --------------------------------------------------------------------------
# dep_version_diff_text -- the artifact that ends up in the ticket body
# --------------------------------------------------------------------------


def test_version_diff_text_renders_each_shape() -> None:
    raw = "alpha\t1.2.3\t1.3.0\nfresh\t(none)\t9.9.9\ngone\t1.0.0\t(none)"
    out = _run(f"dep_version_diff_text requirements.lock {shlex.quote(raw)}").stdout
    assert out.startswith("VERSION DIFF (requirements.lock -> candidate):")
    assert re.search(r"^ {4}alpha +1\.2\.3 -> 1\.3\.0$", out, re.MULTILINE)
    assert re.search(r"^ {2}\+ fresh +9\.9\.9$", out, re.MULTILINE)
    assert re.search(r"^ {2}- gone +1\.0\.0 \(removed\)$", out, re.MULTILINE)


def test_version_diff_text_says_no_change_on_empty_input() -> None:
    out = _run('dep_version_diff_text requirements.lock ""').stdout
    assert out.strip() == (
        "VERSION DIFF: no change -- candidate lock is identical to requirements.lock"
    )


# --------------------------------------------------------------------------
# dep_all_patch_level_only -- the noise gate
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("raw", "patch_only"),
    [
        # Plain patch bumps on every line -- the one case that suppresses filing.
        ("alpha\t1.2.3\t1.2.9", True),
        ("alpha\t1.2.3\t1.2.9\nbeta\t0.1.0\t0.1.1", True),
        # A single non-patch move poisons the whole set.
        ("alpha\t1.2.3\t1.2.9\nbeta\t0.1.0\t0.2.0", False),
        ("alpha\t1.2.3\t1.3.0", False),
        ("alpha\t1.2.3\t2.2.3", False),
        # Additions and removals are never patch-only.
        ("fresh\t(none)\t9.9.9", False),
        ("gone\t1.0.0\t(none)", False),
        # No changes at all -- false, so the skip-reason ordering owns that path.
        ("", False),
        # Numeric comparison, not a string-prefix comparison.
        ("alpha\t1.2.0\t1.20.0", False),
        ("alpha\t2.1.3\t2.10.0", False),
        # Unparseable leading major.minor is conservatively NOT patch-only, so an
        # unreadable version shape can only ever cost noise, never a missed eval.
        ("alpha\t1!2.3.4\t1!2.3.5", False),
        ("alpha\t2024\t2025", False),
        ("alpha\tunknown\t1.2.3", False),
    ],
)
def test_noise_gate(raw: str, patch_only: bool) -> None:
    got = _run(f"dep_all_patch_level_only {shlex.quote(raw)}")
    assert (got.returncode == 0) is patch_only, got.stdout + got.stderr


# --------------------------------------------------------------------------
# dep_stub_skip_reason -- the filing decision update-deps.sh actually consults
# --------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("no_file", "raw", "expect"),
    [
        # A real, non-patch move is the ONLY combination that files.
        (0, "alpha\t1.2.3\t1.3.0", None),
        (0, "fresh\t(none)\t9.9.9", None),
        # Each skip reason, and the order they win in.
        (0, "", "no version changes"),
        (0, "alpha\t1.2.3\t1.2.4", "patch-level only"),
        (1, "alpha\t1.2.3\t1.3.0", "--no-file set"),
        (1, "", "--no-file set"),  # --no-file outranks every later reason
        (1, "alpha\t1.2.3\t1.2.4", "--no-file set"),
    ],
)
def test_stub_skip_reason(no_file: int, raw: str, expect: str | None) -> None:
    got = _run(f"dep_stub_skip_reason {no_file} {shlex.quote(raw)}")
    if expect is None:
        assert got.returncode != 0, f"expected FILE, got skip: {got.stdout!r}"
        assert got.stdout.strip() == ""
    else:
        assert got.returncode == 0, got.stderr
        assert expect in got.stdout


# --------------------------------------------------------------------------
# The caller wiring -- the actual lode-i642 defect
# --------------------------------------------------------------------------


def test_update_deps_never_assigns_changes_raw_in_a_function() -> None:
    """CHANGES_RAW must be assigned at top level, never from inside a function.

    This is the caller-side half of the shipped defect, and no test of the library
    can reach it: a function that sets CHANGES_RAW is fine in isolation and useless
    in update-deps.sh, because every call site is a command substitution running in
    a subshell. An indented assignment is the syntactic tell.
    """
    body = UPDATE_DEPS.read_text(encoding="utf-8")
    assigns = re.findall(r"^([ \t]*)CHANGES_RAW=", body, re.MULTILINE)
    assert assigns, "update-deps.sh no longer assigns CHANGES_RAW"
    assert all(indent == "" for indent in assigns), (
        "CHANGES_RAW is assigned from inside a block/function -- if that is a "
        "function body, the value dies in the command substitution's subshell"
    )


def test_update_deps_sources_the_library() -> None:
    body = UPDATE_DEPS.read_text(encoding="utf-8")
    assert "scripts/dep-churn-lib.sh" in body
    for fn in ("dep_changes_raw", "dep_version_diff_text", "dep_stub_skip_reason"):
        assert fn in body, f"update-deps.sh stopped using {fn}"
